ProyectoVF/ProyectoVF/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoVF.Models;
using ProyectoVF.Services;

namespace ProyectoVF.Controllers
{
    public class CatalogoController : Controller
    {
        private readonly ICatalogo _catalogo;
        private readonly IProducto _producto;
        public CatalogoController(ICatalogo catalogo, IProducto producto)
        {
            _catalogo = catalogo;
            _producto = producto;
        }
        public IActionResult Catalogo(string filtro)
        {
            var productos = _producto.GetProducts();
            switch (filtro)
            {
                case "Id":
                    productos = productos.OrderBy(p => p.IdProducto).ToList();
                    break;
                case "precio":
                    productos = productos.OrderBy(p => p.PrecioProducto).ToList();
                    break;
                case "Categoria":
                    productos = productos.OrderBy(p => p.IdCategoria).ToList();
                    break;
                case "Nombre":
                    productos = productos.OrderBy(p => p.NombreProducto).ToList();
                    break;
                default:
                    break;
            }
            return View(productos);
        }

        [Route("Catalogo/Modificar/{id}")]
        public IActionResult Modificar(int id)
        {
            return View(_catalogo.IDPRODUCTO(id));
        }

        public IActionResult changeDetails(Product obj)
        {
            _catalogo.modificarInfo(obj);
            return RedirectToAction("VistaAdmin","Login");
        }

        [Route("Catalogo/Eliminar/{id}")]
        public IActionResult Eliminar(int id)
        {
            _catalogo.remove(id);
            return RedirectToAction("VistaAdmin", "Login");
        }
    }
}

ProyectoVF/ProyectoVF/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoVF.Services;

namespace ProyectoVF.Controllers
{
    public class MainController : Controller
    {
        private readonly IProducto _producto;
        public MainController(IProducto producto)
        {
            _producto = producto;
        }
        public IActionResult Index()
        {
            return View(_producto.GetProducts());
        }
        [Route("Main/Detalle/{codigo}")]
        public IActionResult Detalle(int codigo)
        {
            ViewData["cod"] = codigo;
            return View(_producto.GetProductById(codigo));
        }
    }
}

ProyectoVF/ProyectoVF/Controllers/ProyectoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoVF.Models;

namespace ProyectoVF.Controllers
{
    public class ProyectoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //No borrar
        public IActionResult Informe()
        {
            return View();
        }
     
        //No borrar
        public IActionResult Contacto()
        {
            return View();
        }
    }
}

ProyectoVF/ProyectoVF/Views/Main/Detalle.cshtml
@model ProyectoVF.Models.Product
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
</head>
<body>
    <div class="card">
        <div class="card-header">
            <img src="@Model.ImgProducto" class="card-img-top" title="@Model.NombreProducto" style="height: 200px; width: 150px">
        </div>
        <div class="card-body">
            <h1>@Model.IdProducto</h1>
            <h1>@Model.NombreProducto</h1>
            <h1>@Model.DesProducto</h1>
            <h1>s/@Model.PrecioProducto</h1>
        </div>
        <div class="card-footer">
            <form asp-controller="Cart" asp-action="Index" method="post">
                <input type="hidden" name="idProducto" value="@Model.IdProducto" />
                <input type="hidden" name="nomProducto" value="@Model.NombreProducto" />
                <input type="hidden" name="desProducto" value="@Model.DesProducto" />
                <input type="hidden" name="preProducto" value="@Model.PrecioProducto" />
                <input type="submit" value="Add cart" />
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag-plus" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 7.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0v-1.5H6a.5.5 0 0 1 0-1h1.5V8a.5.5 0 0 1 .5-.5z" />
                    <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z" />
                </svg>
            </form>
            @if (TempData["Message"] != null)
            {
                <div class="alert alert-warning">@TempData["Message"]</div>
            }
        </div>
    </div>
</body>
</html>

ProyectoVF/ProyectoVF/Views/Main/Index.cshtml
@model IEnumerable<ProyectoVF.Models.Product>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>

<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>
<body>
    <div class="TODO">
        <div class="Cabecera">
            <img src="https://www.velvetboutique.gr/wp-content/uploads/2022/09/logo-velvetboutique-v1-450px.png" alt="ImagenVelvet" />
            <header>
                <nav>
                    <a href="#" class="NmStore">VELVET</a>
                    <a asp-controller="Catalogo" asp-action="Catalogo">CATÁLOGO</a>
                    <a asp-controller="Login" asp-action="Login">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" />
                        </svg>
                    </a>
                    <a asp-controller="Cart" asp-action="CartDetails">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L22.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        <a asp-action="Informe" asp-controller="Proyecto">☰</a>
                    </a>
                </nav>
            </header>
        </div>
        <h2 class="mt-5">PRODUCTOS</h2>
        <div class="container card-container">
            @foreach (var item in Model.Take(8))
            {
                <div class="row">
                    <div class="card" style="width: 15rem; height: 25rem">
                        <div class="card-header">
                            <a asp-action="Detalle" asp-route-id="@item.IdProducto">
                                <img src="@item.ImgProducto" class="card-img-top" title="@item.NombreProducto" style="height: 200px; width: 150px">
                            </a>
                        </div>
                        <div class="card-content">
                            <h5 class="card-text">@item.IdProducto</h5>
                            <h5 class="card-text">@item.PrecioProducto</h5>
                            <h5 class="card-text">@item.NombreProducto</h5>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>